### ISSUE TITLE
Rewrite with Vue.js

### ISSUE THREAD

**Issue by Mittelblut9** [dumpus-app/dumpus-landing#3]
👋
Using plain HTML and CSS can result in duplicate code, slow sites and more maintenance issues.

Vue is modern, fast, easy to maintain and you can use code in multiple sites and components without having to re-create it or copy and paste.

I could do this because I have experience with Vue.🙂

**Comment by Androz2091** [comment]
Oh really? Definitely... if you know how to code the website with Vue (or Svelte which is even faster for this type of app) it would be awesome

We currently have to update the navigation bar in every single page each time 😅

It's not very clean...
